spring.application.name=demoForJpa
server.port=8081
spring.datsource.platform=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/sample_schema
spring.datasource.username=root
spring.datasource.password=0306
spring.datasource.driver-class-name =com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql: true
